name: Release

on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: add-harvest-button-to-monday-pulse-for-chrome
          extra-files: |
            manifest.json

      - name: Use Node.js v18
        if: ${{ steps.release.outputs.release_created == true }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        if: ${{ steps.release.outputs.release_created == true }}
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm
        if: ${{ steps.release.outputs.release_created == true }}
        run: npm ci

      - name: Build npm
        if: ${{ steps.release.outputs.release_created == true }}
        run: npm build

      - name: Create archive
        if: ${{ steps.release.outputs.release_created == true }}
        run: mv ./dist ./${{ github.event.repository.name }}-${{ steps.release.outputs.tag_name }} && zip -r ${{ github.event.repository.name }}-${{ steps.release.outputs.tag_name }}.zip

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./${{ github.event.repository.name }}-${{ steps.release.outputs.tag_name }}.zip
